[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 2


[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 3

[[main]]
  identifier = "showcase"
  name = "showcase"
  url = "showcase"
  weight = 4
